apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: roadwatch

resources:
  - ../../base

patches:
  - path: configmap-app-patch.yaml
  - path: configmap-cluster-patch.yaml
  - path: resource-limits-patch.yaml
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: gateway-hpa
        namespace: roadwatch
      spec:
        minReplicas: 2
        maxReplicas: 10
    target:
      kind: HorizontalPodAutoscaler
      name: gateway-hpa

replacements:
  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.FABRIC_HOST_IP
    targets:
      - select:
          kind: Deployment
          name: fabric-anchor
        fieldPaths:
          - spec.template.spec.hostAliases.0.ip
