import type { EscalationRecord, EscalationTier } from './EscalationRecord.js';

// Complaint shape used by the escalation subsystem (service-layer DTO, not domain entity)
export interface EscalationComplaint {
  ID: string;
  citizenId: string;
  category: string;
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  status: string;
  submittedAt: number;
  assignedAuthorityId: string;
  description: string;
  location: { latitude: number; longitude: number; address?: string };
  mediaUrls?: string[];
  actionHistory?: unknown[];
  escalationHistory?: unknown[];
}

export interface EscalationAction {
  complaint: EscalationComplaint;
  fromAuthorityId: string;
  toAuthorityId: string;
  tier: EscalationTier;
  reason: string;
}

export class EscalationEngine {
  static checkAllDue(complaints: EscalationComplaint[], now: number, adapter: {
    getSlaHours(category: string, priority: string): number;
    routingTable: { hierarchy?: Record<string, string | string[]> };
  }): EscalationAction[] {
    const actions: EscalationAction[] = [];

    for (const complaint of complaints) {
      const slaHours = adapter.getSlaHours(complaint.category, complaint.priority);
      const overdueThreshold = complaint.submittedAt + slaHours * 60 * 60 * 1000;

      if (now > overdueThreshold && complaint.status !== 'RESOLVED' && complaint.status !== 'CLOSED') {
        const hoursOverdue = (now - overdueThreshold) / (60 * 60 * 1000);
        const tier: EscalationTier = hoursOverdue <= 24 ? 1 : hoursOverdue <= 72 ? 2 : 3;
        const nextAuthority = this.getNextTier(complaint.assignedAuthorityId, adapter.routingTable);

        if (nextAuthority) {
          actions.push({
            complaint,
            fromAuthorityId: complaint.assignedAuthorityId,
            toAuthorityId: nextAuthority,
            tier,
            reason: `Complaint overdue by ${Math.floor(hoursOverdue)} hours. SLA breach detected.`,
          });
        }
      }
    }

    return actions;
  }

  static buildEscalationRecord(
    complaint: EscalationComplaint,
    fromAuthority: string,
    toAuthority: string,
    reason: string,
    tier: EscalationTier,
    autoGenerated: boolean,
    fabricTxId = '',
    deliveryStatus: 'Sent' | 'Delivered' | 'Failed' = 'Sent',
    sentAt = Date.now(),
  ): EscalationRecord {
    return {
      id: `${complaint.ID}-${tier}-${sentAt}`,
      complaintId: complaint.ID,
      fromAuthorityId: fromAuthority,
      toAuthorityId: toAuthority,
      tier,
      reason,
      sentAt,
      deliveryStatus,
      fabricTxId,
      autoGenerated,
    };
  }

  static shouldPingAgain(lastPing: number, tier: EscalationTier): boolean {
    const pingIntervals: Record<number, number> = {
      1: 24 * 60 * 60 * 1000,
      2: 12 * 60 * 60 * 1000,
      3: 6 * 60 * 60 * 1000,
      4: 3 * 60 * 60 * 1000,
    };
    return Date.now() - lastPing >= (pingIntervals[tier] ?? pingIntervals[1] ?? 24 * 60 * 60 * 1000);
  }

  static getNextTier(authority: string, routingTable: { hierarchy?: Record<string, string | string[]> }): string {
    const h = routingTable?.hierarchy;
    if (!h) return '';

    if (Array.isArray(h['district']) && h['district'].includes(authority)) return (h['state'] as string) ?? '';
    if (Array.isArray(h['block']) && h['block'].includes(authority)) return (h['district'] as string[])?.[0] ?? '';
    if (Array.isArray(h['village']) && h['village'].includes(authority)) return (h['block'] as string[])?.[0] ?? '';
    if (h['state'] === authority) return (h['central'] as string) ?? '';
    return '';
  }

  /**
   * Advance one step in a linear authority hierarchy (e.g. NHAI / PWD / municipal arrays).
   * If `current` is missing from the list, assigns the first tier.
   * Returns null when already at the top of the hierarchy.
   */
  static nextInLinearHierarchy(
    current: string,
    hierarchy: string[]
  ): { fromAuthorityId: string; toAuthorityId: string; tier: number } | null {
    if (!hierarchy.length) return null;

    const normalized = String(current ?? '').trim();
    const idx = hierarchy.findIndex(
      (role) => role === normalized || (normalized.length > 0 && normalized.includes(role))
    );

    if (idx === -1) {
      return {
        fromAuthorityId: normalized,
        toAuthorityId: hierarchy[0]!,
        tier: 1,
      };
    }

    if (idx >= hierarchy.length - 1) {
      return null;
    }

    return {
      fromAuthorityId: hierarchy[idx]!,
      toAuthorityId: hierarchy[idx + 1]!,
      tier: idx + 2,
    };
  }

  static calculateChronic(complaint: EscalationComplaint): boolean {
    const ageInDays = (Date.now() - complaint.submittedAt) / (24 * 60 * 60 * 1000);
    const isUnresolved = complaint.status !== 'RESOLVED' && complaint.status !== 'CLOSED';
    const hasMultipleEscalations = ((complaint.escalationHistory?.length) ?? 0) >= 3;
    return ageInDays > 30 && isUnresolved && hasMultipleEscalations;
  }
}
