apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: roadwatch
resources:
  - serviceaccounts.yaml
  - peer-authentication.yaml
  - authorization-policies.yaml
  - destination-rules.yaml
  - pdbs.yaml
