# deploy-kind.ps1 — Build images, create kind cluster, load images, apply manifests
#
# Usage (run from repo root):
#   .\k8s\deploy-kind.ps1                   # full deploy
#   .\k8s\deploy-kind.ps1 -Reset            # delete cluster first, then full deploy
#   .\k8s\deploy-kind.ps1 -SkipBuild        # skip docker build (use cached images)
#   .\k8s\deploy-kind.ps1 -InfraOnly        # infra (postgres/redis/kafka) only
#
# Fabric anchor consumer needs the Fabric peer TLS cert and a user X.509
# identity. Before running this script, set the following env vars OR let
# the script prompt you for the paths:
#
#   $env:FABRIC_TLS_CERT_PATH  = path to peer0.nhai.roadwatch.com TLS CA cert
#                                e.g. fabric\network\organizations\peerOrganizations\
#                                       nhai.roadwatch.com\peers\
#                                       peer0.nhai.roadwatch.com\tls\ca.crt
#   $env:FABRIC_X509_CERT_PATH = path to user signing cert (cert.pem)
#   $env:FABRIC_X509_KEY_PATH  = path to user private key  (key.pem)
#
# These are generated by fabric/network/scripts/start.sh + enroll.
# If the Fabric network is not up yet, use -SkipFabricCerts to skip
# creating the fabric-certs Secret (fabric-anchor-consumer will crash-loop
# until you create it later with: kubectl apply -f k8s/fabric-certs-secret.yaml)

param(
    [switch]$Reset,           # Delete and recreate the cluster from scratch
    [switch]$SkipBuild,       # Skip docker build steps (use cached images)
    [switch]$InfraOnly,       # Apply infra (postgres/redis/kafka) only, skip apps
    [switch]$SkipFabricCerts  # Skip creating the fabric-certs Secret
)

$ErrorActionPreference = "Stop"
Set-Location (Split-Path -Parent $PSScriptRoot)   # ensure we're at repo root

$CLUSTER_NAME = "roadwatch"
$NS           = "roadwatch"

function Write-Step([string]$msg) {
    Write-Host ""
    Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
    Write-Host "  $msg" -ForegroundColor Cyan
    Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
}

# ── 0. Reset (optional) ───────────────────────────────────────
if ($Reset) {
    Write-Step "0. Deleting existing kind cluster '$CLUSTER_NAME'..."
    kind delete cluster --name $CLUSTER_NAME 2>$null
    Write-Host "Cluster deleted (or didn't exist)." -ForegroundColor Yellow
}

# ── 1. Create kind cluster ────────────────────────────────────
Write-Step "1. Creating kind cluster '$CLUSTER_NAME'..."
$existing = kind get clusters 2>$null | Where-Object { $_ -eq $CLUSTER_NAME }
if ($existing) {
    Write-Host "Cluster '$CLUSTER_NAME' already exists — skipping creation." -ForegroundColor Yellow
} else {
    kind create cluster --config k8s\kind-config.yaml
    Write-Host "✓ Cluster created." -ForegroundColor Green
}
kubectl config use-context "kind-$CLUSTER_NAME"

# ── 2. Build Docker images ────────────────────────────────────
if (-not $SkipBuild) {
    Write-Step "2. Building Docker images..."

    $builds = @(
        @{ tag = "roadwatch/gateway-api:local";          file = "apps/gateway-api/Dockerfile" },
        @{ tag = "roadwatch/backend-api:local";          file = "backend-api/Dockerfile" },
        @{ tag = "roadwatch/frontend:local";             file = "frontend/Dockerfile" },
        @{ tag = "roadwatch/scheduler:local";            file = "services/scheduler/Dockerfile" },
        @{ tag = "roadwatch/webhook-handler:local";      file = "services/webhook-handler/Dockerfile" },
        @{ tag = "roadwatch/fabric-anchor-consumer:local"; file = "services/fabric-anchor-consumer/Dockerfile" }
    )

    foreach ($b in $builds) {
        Write-Host "  → $($b.tag)..." -ForegroundColor White
        docker build -t $b.tag -f $b.file .
        if ($LASTEXITCODE -ne 0) {
            Write-Host "✗ Build failed for $($b.tag)" -ForegroundColor Red
            exit 1
        }
    }
    Write-Host "✓ All images built." -ForegroundColor Green
} else {
    Write-Host "Skipping image build (-SkipBuild)." -ForegroundColor Yellow
}

# ── 3. Load images into kind ──────────────────────────────────
Write-Step "3. Loading images into kind cluster..."
$images = @(
    "roadwatch/gateway-api:local",
    "roadwatch/backend-api:local",
    "roadwatch/frontend:local",
    "roadwatch/scheduler:local",
    "roadwatch/webhook-handler:local",
    "roadwatch/fabric-anchor-consumer:local"
)
foreach ($img in $images) {
    Write-Host "  → $img..." -ForegroundColor White
    kind load docker-image $img --name $CLUSTER_NAME
}
Write-Host "✓ Images loaded." -ForegroundColor Green

# ── 4. Namespace + ConfigMap + Secrets ───────────────────────
Write-Step "4. Applying namespace, configmap, secrets..."

kubectl apply -f k8s/namespace.yaml

# Postgres init SQL as a ConfigMap (from the actual init.sql file)
kubectl create configmap postgres-init-sql `
    --from-file=init.sql=docker/postgres/init.sql `
    --namespace $NS `
    --dry-run=client -o yaml | kubectl apply -f -

kubectl apply -f k8s/configmap-infra.yaml
kubectl apply -f k8s/configmap-app.yaml
kubectl apply -f k8s/secret.yaml

# ── 4b. Fabric certs Secret ───────────────────────────────────
# fabric-anchor-consumer mounts TLS + X.509 identity from this Secret.
# Skip if -SkipFabricCerts is set (e.g. Fabric network not started yet).
if (-not $SkipFabricCerts) {
    Write-Host ""
    Write-Host "  Creating fabric-certs Secret..." -ForegroundColor White

    # Resolve cert paths: use env vars if set, otherwise use defaults relative to repo root
    $defaultTls  = "fabric\network\organizations\peerOrganizations\nhai.roadwatch.com\peers\peer0.nhai.roadwatch.com\tls\ca.crt"
    $defaultCert = "fabric\network\organizations\peerOrganizations\nhai.roadwatch.com\users\Admin@nhai.roadwatch.com\msp\signcerts\cert.pem"
    $defaultKey  = "fabric\network\organizations\peerOrganizations\nhai.roadwatch.com\users\Admin@nhai.roadwatch.com\msp\keystore\priv_sk"

    $tlsCert  = if ($env:FABRIC_TLS_CERT_PATH)  { $env:FABRIC_TLS_CERT_PATH }  else { $defaultTls }
    $mspCert  = if ($env:FABRIC_X509_CERT_PATH) { $env:FABRIC_X509_CERT_PATH } else { $defaultCert }
    $mspKey   = if ($env:FABRIC_X509_KEY_PATH)  { $env:FABRIC_X509_KEY_PATH }  else { $defaultKey }

    foreach ($f in @($tlsCert, $mspCert, $mspKey)) {
        if (-not (Test-Path $f)) {
            Write-Host ""
            Write-Host "  ⚠  Fabric cert not found: $f" -ForegroundColor Yellow
            Write-Host "     Start the Fabric network first:  fabric\network\scripts\start.sh" -ForegroundColor Yellow
            Write-Host "     Then re-run without -SkipFabricCerts, or set FABRIC_TLS_CERT_PATH," -ForegroundColor Yellow
            Write-Host "     FABRIC_X509_CERT_PATH, FABRIC_X509_KEY_PATH and re-run." -ForegroundColor Yellow
            Write-Host "     Continuing — fabric-anchor-consumer will crash-loop until the Secret exists." -ForegroundColor Yellow
            $SkipFabricCerts = $true
            break
        }
    }

    if (-not $SkipFabricCerts) {
        kubectl create secret generic fabric-certs `
            --from-file=tls-ca.crt=$tlsCert `
            --from-file=msp-cert.pem=$mspCert `
            --from-file=msp-key.pem=$mspKey `
            --namespace $NS `
            --dry-run=client -o yaml | kubectl apply -f -
        Write-Host "  ✓ fabric-certs Secret created." -ForegroundColor Green
    }
} else {
    Write-Host "  Skipping fabric-certs Secret (-SkipFabricCerts)." -ForegroundColor Yellow
}

# ── 4c. Detect Docker host IP for Fabric peer hostAlias ───────
# kind nodes are Docker containers. The Fabric peer runs on the host and is
# exposed on port 17051. From inside a kind node the host is reachable at
# the Docker bridge gateway IP (typically 172.17.0.1 on Linux / host.docker.internal on Docker Desktop).
#
# On Windows with Docker Desktop, host.docker.internal always resolves
# inside containers, but kind nodes may not have that entry in /etc/hosts.
# We detect the gateway IP of the kind node and inject it via hostAliases.
Write-Host ""
Write-Host "  Detecting Docker host IP for Fabric peer hostAliases..." -ForegroundColor White

# Get the IP of the kind control-plane node's default gateway (= Docker host)
$FABRIC_HOST_IP = (docker inspect roadwatch-control-plane `
    --format "{{range .NetworkSettings.Networks}}{{.Gateway}}{{end}}" 2>$null) | Select-Object -First 1

if (-not $FABRIC_HOST_IP -or $FABRIC_HOST_IP -eq "") {
    # Fallback: use host.docker.internal which Docker Desktop injects on Windows/Mac
    $FABRIC_HOST_IP = "host-gateway"
    Write-Host "  Could not detect gateway IP, using 'host-gateway' placeholder." -ForegroundColor Yellow
    Write-Host "  If fabric-anchor-consumer can't reach the peer, set FABRIC_HOST_IP manually." -ForegroundColor Yellow
} else {
    Write-Host "  ✓ Docker host IP: $FABRIC_HOST_IP" -ForegroundColor Green
}

$env:FABRIC_HOST_IP = $FABRIC_HOST_IP

# ── 5. Infrastructure ─────────────────────────────────────────
Write-Step "5. Deploying infrastructure (Postgres, PgBouncer, Redis, Kafka)..."
kubectl apply -f k8s/postgres.yaml
kubectl apply -f k8s/pgbouncer.yaml
kubectl apply -f k8s/redis.yaml
kubectl apply -f k8s/kafka.yaml

Write-Host "Waiting for Postgres  (up to 120s)..." -ForegroundColor Blue
kubectl wait --for=condition=ready pod -l app=postgres   -n $NS --timeout=120s

Write-Host "Waiting for PgBouncer (up to 60s)..."  -ForegroundColor Blue
kubectl wait --for=condition=ready pod -l app=pgbouncer  -n $NS --timeout=60s

Write-Host "Waiting for Redis     (up to 60s)..."  -ForegroundColor Blue
kubectl wait --for=condition=ready pod -l app=redis      -n $NS --timeout=60s

Write-Host "Waiting for Kafka     (up to 120s)..." -ForegroundColor Blue
kubectl wait --for=condition=ready pod -l app=kafka      -n $NS --timeout=120s

if ($InfraOnly) {
    Write-Host "InfraOnly mode — stopping here." -ForegroundColor Yellow
    exit 0
}

# ── 6. Application services ───────────────────────────────────
Write-Step "6. Deploying application services..."
kubectl apply -f k8s/gateway-api.yaml
kubectl apply -f k8s/backend-api.yaml
kubectl apply -f k8s/frontend.yaml

# services.yaml contains scheduler, webhook-handler, and fabric-anchor-consumer.
# fabric-anchor-consumer has a hostAliases entry with ${FABRIC_HOST_IP} that
# must be substituted before apply. We use PowerShell string replacement
# since envsubst may not be available on Windows.
$servicesYaml = Get-Content k8s\services.yaml -Raw
$servicesYaml = $servicesYaml.Replace('${FABRIC_HOST_IP}', $FABRIC_HOST_IP)
$tmpFile = [System.IO.Path]::GetTempFileName() + ".yaml"
$servicesYaml | Set-Content -Path $tmpFile -Encoding UTF8
kubectl apply -f $tmpFile
Remove-Item $tmpFile -ErrorAction SilentlyContinue

Write-Host "Waiting for Gateway API (up to 120s)..." -ForegroundColor Blue
kubectl wait --for=condition=ready pod -l app=gateway -n $NS --timeout=120s

# ── 7. Summary ────────────────────────────────────────────────
Write-Step "7. Deployment complete!"
Write-Host ""
kubectl get pods -n $NS
Write-Host ""
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Green
Write-Host "  ✅ RoadWatch is running on kind!" -ForegroundColor Green
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Green
Write-Host ""
Write-Host "  🌐 Frontend:    http://localhost:8080" -ForegroundColor White
Write-Host "  🔌 Gateway API: http://localhost:3100" -ForegroundColor White
Write-Host "  🔧 Backend API: http://localhost:4001" -ForegroundColor White
Write-Host ""
Write-Host "  Fabric peer (Docker host): peer0.nhai.roadwatch.com:17051" -ForegroundColor White
Write-Host "  Fabric host IP injected:   $FABRIC_HOST_IP" -ForegroundColor White
Write-Host ""
Write-Host "  Useful commands:" -ForegroundColor Yellow
Write-Host "    kubectl get pods -n roadwatch"
Write-Host "    kubectl logs -n roadwatch deploy/gateway -f"
Write-Host "    kubectl logs -n roadwatch deploy/fabric-anchor -f"
Write-Host "    kubectl logs -n roadwatch deploy/scheduler -f"
Write-Host "    kubectl logs -n roadwatch deploy/webhook -f"
Write-Host "    kind delete cluster --name roadwatch          # tear down k8s"
Write-Host "    docker compose -f fabric/network/docker/docker-compose.yaml down  # tear down Fabric"
Write-Host ""
