import { Complaint } from '../domain/Complaint';
import { EscalationRecord, EscalationTier } from '../domain/EscalationRecord';

export interface EscalationAction {
  complaint: Complaint;
  fromAuthorityId: string;
  toAuthorityId: string;
  tier: EscalationTier;
  reason: string;
}

export class EscalationEngine {
  static checkAllDue(complaints: Complaint[], now: number, adapter: any): EscalationAction[] {
    const actions: EscalationAction[] = [];
    
    for (const complaint of complaints) {
      // Check if complaint is overdue based on SLA
      const slaHours = adapter.getSlaHours(complaint.category, complaint.priority);
      const overdueThreshold = complaint.submittedAt + (slaHours * 60 * 60 * 1000);
      
      if (now > overdueThreshold && complaint.status !== 'RESOLVED' && complaint.status !== 'CLOSED') {
        // Determine escalation tier based on how overdue it is
        const hoursOverdue = (now - overdueThreshold) / (60 * 60 * 1000);
        let tier: EscalationTier;
        
        if (hoursOverdue <= 24) {
          tier = 'TIER_1';
        } else if (hoursOverdue <= 72) {
          tier = 'TIER_2';
        } else {
          tier = 'TIER_3';
        }
        
        // Get next authority in hierarchy
        const nextAuthority = this.getNextTier(complaint.assignedAuthorityId, adapter.routingTable);
        
        if (nextAuthority) {
          actions.push({
            complaint,
            fromAuthorityId: complaint.assignedAuthorityId,
            toAuthorityId: nextAuthority,
            tier,
            reason: `Complaint overdue by ${Math.floor(hoursOverdue)} hours. SLA breach detected.`
          });
        }
      }
    }
    
    return actions;
  }

  static buildEscalationRecord(
    complaint: Complaint,
    fromAuthority: string,
    toAuthority: string,
    reason: string,
    tier: EscalationTier,
    autoGenerated: boolean,
    fabricTxId: string = '',
    deliveryStatus: 'Sent' | 'Delivered' | 'Failed' = 'Sent',
    sentAt: number = Date.now()
  ): EscalationRecord {
    return {
      id: `${complaint.ID}-${tier}-${sentAt}`,
      complaintId: complaint.ID,
      fromAuthorityId: fromAuthority,
      toAuthorityId: toAuthority,
      tier,
      reason,
      sentAt,
      deliveryStatus,
      fabricTxId,
      autoGenerated
    };
  }

  static shouldPingAgain(lastPing: number, tier: EscalationTier, adapter: any): boolean {
    const now = Date.now();
    const timeSinceLastPing = now - lastPing;
    
    // Define ping intervals based on tier (in milliseconds)
    const pingIntervals = {
      'TIER_1': 24 * 60 * 60 * 1000, // 24 hours
      'TIER_2': 12 * 60 * 60 * 1000, // 12 hours  
      'TIER_3': 6 * 60 * 60 * 1000,  // 6 hours
    };
    
    const interval = pingIntervals[tier] || pingIntervals['TIER_1'];
    return timeSinceLastPing >= interval;
  }

  static getNextTier(authority: string, routingTable: any): string {
    if (!routingTable || !routingTable.hierarchy) {
      return '';
    }
    
    // Find current authority in hierarchy
    const hierarchy = routingTable.hierarchy;
    
    // Check district level escalation
    if (hierarchy.district && hierarchy.district.includes(authority)) {
      return hierarchy.state || '';
    }
    
    // Check block level escalation  
    if (hierarchy.block && hierarchy.block.includes(authority)) {
      return hierarchy.district?.[0] || '';
    }
    
    // Check village level escalation
    if (hierarchy.village && hierarchy.village.includes(authority)) {
      return hierarchy.block?.[0] || '';
    }
    
    // If at state level, escalate to central
    if (hierarchy.state === authority) {
      return hierarchy.central || '';
    }
    
    return '';
  }

  static buildEscalationPayload(complaint: Complaint, tier: EscalationTier, adapter: any): any {
    return {
      complaintId: complaint.ID,
      escalationTier: tier,
      originalSubmissionDate: new Date(complaint.submittedAt).toISOString(),
      currentStatus: complaint.status,
      category: complaint.category,
      priority: complaint.priority,
      location: {
        latitude: complaint.location.latitude,
        longitude: complaint.location.longitude,
        address: complaint.location.address
      },
      description: complaint.description,
      mediaUrls: complaint.mediaUrls || [],
      citizenId: complaint.citizenId,
      escalationReason: `SLA breach - Tier ${tier} escalation required`,
      escalationTimestamp: new Date().toISOString(),
      previousActions: complaint.actionHistory || [],
      urgencyScore: this.calculateUrgencyScore(complaint, tier),
      requiredAction: this.getRequiredActionForTier(tier),
      deadline: this.calculateNewDeadline(tier)
    };
  }
  
  private static calculateUrgencyScore(complaint: Complaint, tier: EscalationTier): number {
    let score = 0;
    
    // Base score by priority
    const priorityScores = { 'LOW': 1, 'MEDIUM': 3, 'HIGH': 5, 'CRITICAL': 8 };
    score += priorityScores[complaint.priority] || 1;
    
    // Tier multiplier
    const tierMultipliers = { 'TIER_1': 1.2, 'TIER_2': 1.5, 'TIER_3': 2.0 };
    score *= tierMultipliers[tier] || 1;
    
    // Age factor
    const ageInDays = (Date.now() - complaint.submittedAt) / (24 * 60 * 60 * 1000);
    score += Math.min(ageInDays * 0.1, 2);
    
    return Math.round(score * 10) / 10;
  }
  
  private static getRequiredActionForTier(tier: EscalationTier): string {
    const actions = {
      'TIER_1': 'Immediate review and status update required within 4 hours',
      'TIER_2': 'Senior authority intervention required within 2 hours', 
      'TIER_3': 'Executive escalation - Resolution required within 1 hour'
    };
    return actions[tier] || 'Review required';
  }
  
  private static calculateNewDeadline(tier: EscalationTier): string {
    const now = new Date();
    const deadlineHours = { 'TIER_1': 4, 'TIER_2': 2, 'TIER_3': 1 };
    const hours = deadlineHours[tier] || 4;
    
    now.setHours(now.getHours() + hours);
    return now.toISOString();
  }

  static calculateChronic(complaint: Complaint): boolean {
    const now = Date.now();
    const ageInDays = (now - complaint.submittedAt) / (24 * 60 * 60 * 1000);
    
    // Consider chronic if:
    // 1. Age > 30 days and still not resolved
    // 2. Has been escalated multiple times (>= 3)
    // 3. Has multiple similar complaints in same area
    
    const isOld = ageInDays > 30;
    const isUnresolved = complaint.status !== 'RESOLVED' && complaint.status !== 'CLOSED';
    const hasMultipleEscalations = (complaint.escalationHistory?.length || 0) >= 3;
    
    return isOld && isUnresolved && hasMultipleEscalations;
  }

  static generateRTIDraft(complaint: Complaint, authority: string, adapter: any): any {
    const now = new Date();
    const rtiDeadline = new Date(now.getTime() + (30 * 24 * 60 * 60 * 1000)); // 30 days from now
    
    return {
      rtiApplicationId: `RTI-${complaint.ID}-${now.getTime()}`,
      complaintReference: complaint.ID,
      applicantDetails: {
        citizenId: complaint.citizenId,
        applicationDate: now.toISOString()
      },
      publicAuthority: authority,
      informationSought: [
        `Current status and action taken on complaint ID: ${complaint.ID}`,
        `Timeline of all actions performed since complaint submission on ${new Date(complaint.submittedAt).toDateString()}`,
        `Reasons for delay in resolution beyond SLA timeline`,
        `Expected completion date for complaint resolution`,
        `Details of any technical or administrative challenges faced`,
        `Escalation history and current authority handling the complaint`
      ],
      reasonForInformation: `Citizen's right to know the status and progress of their complaint regarding ${complaint.category} submitted on ${new Date(complaint.submittedAt).toDateString()}`,
      modeOfReceivingInfo: 'Email and SMS',
      deadline: rtiDeadline.toISOString(),
      feeStatus: 'Exempt under Section 2(f) - relates to citizen grievance',
      urgencyJustification: this.calculateChronic(complaint) ? 
        'Chronic complaint requiring immediate transparency' : 
        'Standard RTI request for complaint status',
      attachments: [
        {
          type: 'complaint_copy',
          description: 'Original complaint submission with media evidence'
        },
        {
          type: 'escalation_history', 
          description: 'Record of all escalations and authority responses'
        }
      ],
      legalBasis: 'Right to Information Act, 2005 - Section 6(1)',
      expectedResponseFormat: 'Detailed written response with supporting documents'
    };
  }
}
