export type EscalationId = string;
export type ComplaintId = string;
export type AuthorityId = string;
export type EscalationTier = 1 | 2 | 3 | 4;
export type Timestamp = number;
export type DeliveryStatus = 'Sent' | 'Delivered' | 'Failed';

export interface EscalationRecord {
  id: EscalationId;
  complaintId: ComplaintId;
  fromAuthorityId: AuthorityId;
  toAuthorityId: AuthorityId;
  tier: EscalationTier;
  reason: string;
  sentAt: Timestamp;
  deliveryStatus: DeliveryStatus;
  fabricTxId: string;
  autoGenerated: boolean;
}
